### ISSUE TITLE
Problems with inheritance when YAML file has line breaks

### ISSUE THREAD

**Issue by bowsersenior** [attinteractive/yacht#22]
Only values for the default environment are loaded when a YAML file has line breaks in it, like so:

```
default:
  key1: foo

  key2: bar

my_env:
  key3: baz
```

Need to investigate to determine the exact types of line breaks that cause this problem. YAML itself supports line breaks:
- http://yaml.org/spec/1.1/#id871136
